version: '3'
services: 
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports: 
      - '8000:8000'
    volumes: 
      - .:/app
  worker:
    build:
      dockerfile: ./worker/Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules