apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-inw-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-inw-staging
  template:
    metadata:
      labels:
        app: api-inw-staging
    spec:
      containers:
      - name: api-inw-staging
        image: gcr.io/appDomain-123456/api-inw-staging:latest
        ports:
        - containerPort: 8000
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: production
                key: MONGODB_URI
          - name: GOOGLE_MAP_API_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: GOOGLE_MAP_API_KEY
          - name: GOOGLE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: default
                key: GOOGLE_PROJECT_ID
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: SENDGRID_API_KEY
          - name: CRON_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: CRON_SECRET_KEY
          - name: ACTIVITY_LOG_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: ACTIVITY_LOG_KEY
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_SECRET
          - name: JWT_ALGORITHM
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_ALGORITHM
          - name: JWT_ISSUER
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_ISSUER
          - name: JWT_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_AUDIENCE
          - name: BRAINTREE_SB_MERCHANT_ID
            valueFrom:
              secretKeyRef:
                name: default
                key: BRAINTREE_SB_MERCHANT_ID
          - name: BRAINTREE_SB_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: BRAINTREE_SB_PUBLIC_KEY
          - name: BRAINTREE_SB_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: BRAINTREE_SB_PRIVATE_KEY
          - name: BRAINTREE_MERCHANT_ID
            valueFrom:
              secretKeyRef:
                name: default
                key: BRAINTREE_MERCHANT_ID
          - name: BRAINTREE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: BRAINTREE_PUBLIC_KEY
          - name: BRAINTREE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: BRAINTREE_PRIVATE_KEY
          - name: RS_USERNAME
            valueFrom:
              secretKeyRef:
                name: default
                key: RS_USERNAME
          - name: RS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: default
                key: RS_PASSWORD
          - name: SSL_KEY_PASS
            valueFrom:
              secretKeyRef:
                name: default
                key: SSL_KEY_PASS
          - name: SENTRY_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: SENTRY_KEY
